# Permalinks
permalink:           pretty

# Setup
title:               Caleigh Minshall
tagline:             Computer Science student at the University of British Columbia
url:                 https://caleighm.github.io
paginate:            5
paginate_path:      "/blog/page:num/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Caleigh Minshall
  url:               https://twitter.com/cjminsh
  email:             minshallc@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/caleighm/caleighm.github.io
twitter:             cjminsh
github:              caleighm
linkedin:            https://linkedin.com/in/caleigh-minshall-00a46522/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
